name: Deploy to GitHub Pages

on:
  push:
    branches:
      - develop  # Trigger the workflow on any push to the 'develop' branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu runner for the job

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checkout the repository code

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'  # Set the Node.js version to 18 (or higher)

    - name: Install dependencies
      run: npm install  # Install project dependencies

    - name: Build the static website
      run: npx parcel build src/index.html --dist-dir dist  # Run the build with the correct path

    - name: Upload build artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './dist'  # Specify the build output directory (where Parcel generates files)

  deploy:
    runs-on: ubuntu-latest  # Use Ubuntu runner for deployment

    needs: build  # Ensure that the 'build' job is completed before this job runs

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checkout the repository code

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4  # Deploy to GitHub Pages
